[package]
name = "losangeles"
version = "0.1.0"
edition = "2021"

[dependencies]
uart_16550 = "0.2.0"
pic8259 = "0.10.1"
x86_64 = "0.14.2"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.9.8"
limine = "0.1.10"